### ISSUE TITLE
Bug when attempting to open link for second time

### ISSUE THREAD

**Issue by RonilPatel7** [Arthur-Milchior/anki-link-to-open-browser#3]
Debug info:
Anki 2.1.24 (359b9f5c) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-04 10:35:07

Caught exception:
Traceback (most recent call last):
File "aqt\webview.py", line 34, in cmd
File "aqt\webview.py", line 114, in _onCmd
File "aqt\webview.py", line 512, in _onBridgeCmd
File "aqt\gui_hooks.py", line 2091, in __call__
File "C:\Users\Ronil Patel\AppData\Roaming\Anki2\addons21\1126950429\browser.py", line 9, in on_bridge_browser
browser = dialogs.open("Browser", mw)
File "aqt\__init__.py", line 86, in open
RuntimeError: wrapped C/C++ object of type AdvancedBrowser has been deleted

**Comment by Arthur-Milchior** [comment]
Do you click twice on it quickly ? Did you close the browser and then opened it again ?
Does it occur everytime or just once ?

Do you have the add-on to open a window multiple time ?

The intuition I have, given the error message, was that you clicked on a link while a/the browser was being closed, and it didn't know how to handle closing and opening simultaneously

**Comment by RonilPatel7** [comment]
I have 3 add ons installed: 1126950429 & 354407385 & 1672832404

I demonstrated the issue in these videos: 
https://www.dropbox.com/s/j4mhtg8f8sphqbf/Issue3%20-%20Links%20with%20Note%20ID.mp4?dl=0

https://www.dropbox.com/s/ls6fmr9t579y7u8/Issue4%20-%20Links%20with%20Note%20ID.mp4?dl=0

**Comment by RonilPatel7** [comment]
I also just noticed that someone commented on youtube with the same bug: https://www.youtube.com/watch?v=zR6qrOD5dAY

**Comment by Arthur-Milchior** [comment]
Epi pushed a correction to the other add-on, open window multiple time; and I put it on ankiweb. should be corrected

**Comment by RonilPatel7** [comment]
Thank you for help in resolving the issues with attempting to open the link for second time.

I am still having issues with copying and pasting the link as described in the first 2 minutes of this video (https://www.dropbox.com/s/ls6fmr9t579y7u8/Issue4%20-%20Links%20with%20Note%20ID.mp4?dl=0)

**Comment by Arthur-Milchior** [comment]
In the form you left "search" to "search query". In this case the "current" button does not work. It works only if you select "note" or "card". If I've time, or if you want Epi to do it, we could ensure that "current" is disabled when "search query" is selected; or that it change "search query" back to "note".

Copy paste works on my computer. I've no idea why it wouldn't elsewhere. Could you maybe try anki with only this add-on and see if it works or not. So that I see whether it's a problem related to an interaction between add-ons or if it's a problem of this add-on itself.
